server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.14.57:3306/sg_blog?useUnicode=true&characterEncoding=UTF-8
    username: sq
    password: 123456
  redis:
    # Redis本地服务器地址，注意要开启redis服务，即那个redis-server.exe
    host: 8.130.14.57
    # Redis服务器端口,默认为6379.若有改动按改动后的来
    port: 6379
    #Redis服务器连接密码，默认为空，若有设置按设置的来
    password: SHIquan8023
    lettuce:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 8
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-prefix: sg_



oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:




